#include "error_handler.h"
#include "logger.h"
#include <unordered_map>

const char* XrResultToString(XrResult result) {
    static std::unordered_map<XrResult, const char*> resultMap = {
        {XR_SUCCESS, "XR_SUCCESS"},
        {XR_ERROR_VALIDATION_FAILURE, "XR_ERROR_VALIDATION_FAILURE"},
        {XR_ERROR_RUNTIME_FAILURE, "XR_ERROR_RUNTIME_FAILURE"},
        {XR_ERROR_OUT_OF_MEMORY, "XR_ERROR_OUT_OF_MEMORY"},
        {XR_ERROR_INSTANCE_LOST, "XR_ERROR_INSTANCE_LOST"},
        {XR_ERROR_SESSION_RUNNING, "XR_ERROR_SESSION_RUNNING"},
        {XR_ERROR_SESSION_NOT_RUNNING, "XR_ERROR_SESSION_NOT_RUNNING"},
        {XR_ERROR_SESSION_LOST, "XR_ERROR_SESSION_LOST"},
        {XR_ERROR_SYSTEM_INVALID, "XR_ERROR_SYSTEM_INVALID"},
        {XR_ERROR_PATH_INVALID, "XR_ERROR_PATH_INVALID"},
        {XR_ERROR_PATH_COUNT_EXCEEDED, "XR_ERROR_PATH_COUNT_EXCEEDED"},
        {XR_ERROR_PATH_FORMAT_INVALID, "XR_ERROR_PATH_FORMAT_INVALID"},
        {XR_ERROR_PATH_UNSUPPORTED, "XR_ERROR_PATH_UNSUPPORTED"},
        {XR_ERROR_LAYER_INVALID, "XR_ERROR_LAYER_INVALID"},
        {XR_ERROR_LAYER_LIMIT_EXCEEDED, "XR_ERROR_LAYER_LIMIT_EXCEEDED"},
        {XR_ERROR_SWAPCHAIN_RECT_INVALID, "XR_ERROR_SWAPCHAIN_RECT_INVALID"},
        {XR_ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED, "XR_ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED"},
        {XR_ERROR_ACTION_TYPE_MISMATCH, "XR_ERROR_ACTION_TYPE_MISMATCH"},
        {XR_ERROR_SESSION_NOT_READY, "XR_ERROR_SESSION_NOT_READY"},
        {XR_ERROR_SESSION_NOT_STOPPING, "XR_ERROR_SESSION_NOT_STOPPING"},
        {XR_ERROR_TIME_INVALID, "XR_ERROR_TIME_INVALID"},
        {XR_ERROR_REFERENCE_SPACE_UNSUPPORTED, "XR_ERROR_REFERENCE_SPACE_UNSUPPORTED"},
        {XR_ERROR_FILE_ACCESS_ERROR, "XR_ERROR_FILE_ACCESS_ERROR"},
        {XR_ERROR_FILE_CONTENT_INVALID, "XR_ERROR_FILE_CONTENT_INVALID"},
        {XR_ERROR_FORM_FACTOR_UNSUPPORTED, "XR_ERROR_FORM_FACTOR_UNSUPPORTED"},
        {XR_ERROR_FORM_FACTOR_UNAVAILABLE, "XR_ERROR_FORM_FACTOR_UNAVAILABLE"},
        {XR_ERROR_API_LAYER_NOT_PRESENT, "XR_ERROR_API_LAYER_NOT_PRESENT"},
        {XR_ERROR_CALL_ORDER_INVALID, "XR_ERROR_CALL_ORDER_INVALID"},
        {XR_ERROR_HANDLE_INVALID, "XR_ERROR_HANDLE_INVALID"},
        {XR_ERROR_INSTANCE_LOST, "XR_ERROR_INSTANCE_LOST"},
        {XR_ERROR_SESSION_LOST, "XR_ERROR_SESSION_LOST"},
        {XR_ERROR_RUNTIME_UNAVAILABLE, "XR_ERROR_RUNTIME_UNAVAILABLE"},
        {XR_ERROR_FEATURE_UNSUPPORTED, "XR_ERROR_FEATURE_UNSUPPORTED"},
        {XR_ERROR_EXTENSION_NOT_PRESENT, "XR_ERROR_EXTENSION_NOT_PRESENT"},
        {XR_ERROR_LIMIT_REACHED, "XR_ERROR_LIMIT_REACHED"},
        {XR_ERROR_SIZE_INSUFFICIENT, "XR_ERROR_SIZE_INSUFFICIENT"},
        {XR_ERROR_HANDLE_INVALID, "XR_ERROR_HANDLE_INVALID"},
        {XR_ERROR_INSTANCE_LOST, "XR_ERROR_INSTANCE_LOST"},
        {XR_ERROR_SESSION_LOST, "XR_ERROR_SESSION_LOST"},
        {XR_ERROR_FUNCTION_UNSUPPORTED, "XR_ERROR_FUNCTION_UNSUPPORTED"},
        {XR_ERROR_FEATURE_UNSUPPORTED, "XR_ERROR_FEATURE_UNSUPPORTED"},
        {XR_ERROR_EXTENSION_NOT_PRESENT, "XR_ERROR_EXTENSION_NOT_PRESENT"},
        {XR_ERROR_LIMIT_REACHED, "XR_ERROR_LIMIT_REACHED"},
        {XR_ERROR_SIZE_INSUFFICIENT, "XR_ERROR_SIZE_INSUFFICIENT"},
        {XR_ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED, "XR_ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED"},
        {XR_ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED, "XR_ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED"},
        {XR_ERROR_NAME_DUPLICATED, "XR_ERROR_NAME_DUPLICATED"},
        {XR_ERROR_NAME_INVALID, "XR_ERROR_NAME_INVALID"},
        {XR_ERROR_ACTIONSET_NOT_ATTACHED, "XR_ERROR_ACTIONSET_NOT_ATTACHED"},
        {XR_ERROR_ACTIONSETS_ALREAD_ATTACHED, "XR_ERROR_ACTIONSETS_ALREAD_ATTACHED"},
        {XR_ERROR_LOCALIZED_NAME_DUPLICATED, "XR_ERROR_LOCALIZED_NAME_DUPLICATED"},
        {XR_ERROR_LOCALIZED_NAME_INVALID, "XR_ERROR_LOCALIZED_NAME_INVALID"},
        {XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING, "XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING"},
        {XR_ERROR_RUNTIME_UNAVAILABLE, "XR_ERROR_RUNTIME_UNAVAILABLE"},
    };
    
    auto it = resultMap.find(result);
    if (it != resultMap.end()) {
        return it->second;
    }
    
    return "UNKNOWN_XR_RESULT";
}

void LogXrError(XrResult result, const char* function, const char* file, int line) {
    if (result != XR_SUCCESS) {
        LOGE("OpenXR error in %s (%s:%d): %s", function, file, line, XrResultToString(result));
    }
}

